version: '3.8'

networks:
  gf:
    external : true

services:

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - LABEL_REFRESH_INTERVAL=30s
    volumes:
      - ./loki/:/etc/loki/
    networks:
      - gf

# configurated for pushing journal and nginx logs
  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /var/log/journal/:/var/log/journal/
      - /run/log/journal/:/run/log/journal/
      - /etc/machine-id:/etc/machine-id
      - ./promtail.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - gf
