global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: dev-push-gateway
    metrics_path: /metrics
    scheme: http
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ["pushgateway:9091"]
        labels:
          service: "prom-pushgateway"

